-- books seeding
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    pages INTEGER,
    deletedAt TIMESTAMP
);

INSERT INTO books (name, pages) VALUES ('Introduction to Spring Boot', 200);
INSERT INTO books (name, pages) VALUES ('Java in Practice', 300);

-- authors seeding
CREATE TABLE IF NOT EXISTS authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    age INTEGER
);

INSERT INTO authors (name, age) VALUES ('WN', 25);

-- books_authors seeding
CREATE TABLE IF NOT EXISTS books_authors (
    book_id BIGINT,
    author_id BIGINT,
    PRIMARY KEY (book_id, author_id),
    FOREIGN KEY (book_id) REFERENCES books(id),
    FOREIGN KEY (author_id) REFERENCES authors(id)
);

INSERT INTO books_authors (book_id, author_id) VALUES (1, 1);
INSERT INTO books_authors (book_id, author_id) VALUES (2, 1);
